### PR TITLE
Proposal

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by mmariuzzo** [comment]
Hi Sergio,

I've checked your optimization and all seems working right. Great!

**Comment by sergiogonzalez** [comment]
Hey @mmariuzzo did you have an LPS ticket created for this? Or should I create a new one? Thx!

**Comment by mmariuzzo** [comment]
Sorry, I miss you comment. Yes, I've created LPS-70834.

**Comment by sergiogonzalez** [comment]
Hey @mmariuzzo perfect. I have gone ahead and created the story ticket for this feature https://issues.liferay.com/browse/LPS-71635 and I have closed the original feature request and now it points at the story.

I'll be very soon on parternity leave for a while, so I sent the pull to @adolfopa and he'll be in charge of sending the pull to Brian to merge it an monitor it in case anything goes wrong. 

In case you want to send any other pull requests during the time I'm gone feel free to send them to him and he'll take care of them.

This is the pull that I sent to Adolfo: https://github.com/adolfopa/liferay-portal/pull/497

Thanks!

**Comment by mmariuzzo** [comment]
Thanks @sergiogonzalez... and congratulation for the paternity. As you know I'm working on DocumentConversion. I'll send the pull to Adolfo

**Pull request merged**
